증권데이터 분석 깃허브 페이지

https://github.com/sharebook-kr/book-pandas-for-finance

In [1]:
!pip install numpy

     --------------------------------------- 14.6/14.6 MB 46.9 MB/s eta 0:00:00


You should consider upgrading via the 'C:\Users\0103t\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.


In [3]:
import numpy as np

넘파이는 행렬이나 다차원 배열을 관리하기 위한 ndarray 객체를 사용한다.

array 함수에 파이썬 리스트를 넘겨주면 ndarray 타입의 객체를 반환한다.

In [5]:
data = [1, 2, 3]
arr = np.array(data)
print(arr)
print(type(arr))

[1 2 3]
<class 'numpy.ndarray'>


arr[row, column] 과 arr[row][column]은 같은 표현.

arr[:,c] : 열벡터 출력 가능.

In [8]:
data2d = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

arr = np.array(data2d)
print(arr[0])   # 행
print(arr[:,0]) # 열

[1 2 3]
[1 4 7]


ndarray 객체는 ,(콤마)없이 print.

In [7]:
data1 = [1, 2, 3, 4]
arr1 = np.array(data1)
print(arr1)
print(type(arr1))

[1 2 3 4]
<class 'numpy.ndarray'>


shape은 ndarray의 크기 정보.
ndim은 차원 정보.
dtype은 데이터 타입.

*shape은 튜플로 저장

In [13]:
data2 = [
    [1, 2],
    [3, 4]
]
arr2 = np.array(data2)
print(arr2, end="\n\n")
print(arr2.shape)
print(arr2.ndim)
print(arr2.dtype)

[[1 2]
 [3 4]]

(2, 2)
2
int32


1차원 데이터는 튜플에 하나의 값이 들어있다.

row의 길이가 아닌 데이터의 길이가 들어있다.

In [14]:
print(arr1.shape)

(4,)


zeros와 ones 함수는 기본적으로 float 타입의 데이터로 저장한다.

In [15]:
size = (3, 4)
print(np.zeros(size))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


arange 함수는 range 함수와 비슷한 기능을 한다.

arange 함수는 실수 범위도 생성할 수 있다.

In [16]:
print(np.arange(5))
print(np.arange(1, 5))
print(np.arange(1, 5, 2))

[0 1 2 3 4]
[1 2 3 4]
[1 3]


reshape 함수는 원본 데이터를 고려해야 한다.

원본 데이터가 맞지 않으면 에러가 발생한다.

In [17]:
ndarr1 = np.arange(6)
ndarr2 = ndarr1.reshape(2, 3)
print(ndarr2)

[[0 1 2]
 [3 4 5]]


대용량의 데이터를 다룰 때는 가능하면 작은 공간에 저장하는 것이 좋다.

dtype안의 kind와 alignment 속성을 사용하면 축약어 정보도 확인할 수 있다.

In [21]:
arr = np.array([1, 2, 3], dtype=np.uint8)
print(arr.dtype)
print(arr.dtype.kind)
print(arr.dtype.alignment)

uint8
u
1


astype 메서드는 새로운 ndarray 객체를 리턴하므로 결과를 변수에 바인딩해서 사용해야 한다.

In [22]:
arr = arr.astype('int8')
print(arr.dtype)

int8


int8은 -128 ~ 127까지만 표현할 수 있기 때문에 255를 표현할 수 없다.

데이터 타입을 변경할 때는 데이터의 범위에 주의해야 한다.

In [23]:
a = np.array([0, 255], dtype = np.uint8)
b = a.astype('int8')
print(a)
print(b)

[  0 255]
[ 0 -1]


높은 비트로 데이터를 표현하는 것이 정확하지만, 저장 공간까지 고려해서 적절한 타입을 선택해야 한다.

데이터의 정확도가 중요한 연산의 겅우에는 실수 연산을 최소화하는 것이 중요하다.

In [24]:
a16 = np.array([1.333333], dtype = np.float16)
a32 = np.array([1.333333], dtype = np.float32)
print(a16)
print(a32)

[1.333]
[1.333333]


In [25]:
a16 = np.array([1.0], dtype = np.float16)
a32 = np.array([1.0], dtype = np.float32)
print(a16/3)
print(a32/3)

[0.3333]
[0.33333334]


nan은 Not-a-Number의 약자로 숫자가 아닌 값 혹은 정의되지 않은 숫자를 의미한다.

inf 혹은 -inf는 무한대의 숫자를 뜻한다.

nan, inf, -inf는 float 형이다.

In [26]:
print(np.nan, type(np.nan))
print(np.inf, type(np.inf))
print(-np.inf, type(-np.inf))

nan <class 'float'>
inf <class 'float'>
-inf <class 'float'>
